apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui-dev
  namespace: guestbook-dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: guestbook-ui-dev
  template:
    metadata:
      labels:
        app: guestbook-ui-dev
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.2
        name: guestbook-ui
        ports:
        - containerPort: 80